### ISSUE TITLE
Nested transitions

### ISSUE THREAD

**Issue by RanzQ** [cheapsteak/react-transition-group-plus#11]
Hi,

This might be a wrong channel to ask but I was inspired by your medium.com post about HOC animations. Have you solved the problem with nested animations? I'm still using the normal ReactTransitionGroup and what I'd like to achieve is something like this:

```
<ReactTransitionGroup>
  <CurrentPage>
    <ReactTransitionGroup>
      <SomeSection />
      <OtherSection />
    </ReactTransitionGroup>
  </CurrentPage>
</ReactTransitionGroup>
```

I haven't found a way to make `SomeSection` appear first and then `OtherSection` to appear with a delay for example. Like in a slide show one could have multiple appearing components per slide.

Your extension is definitely useful for chaining animations but what about nesting like this?

**Comment by cheapsteak** [comment]
Hi Juha

It sounds like you're looking to stagger in two sections?  

I'm not sure if I completely understand the requirement (a codepen or fiddle would be helpful if I'm misunderstanding), but I think I would create a ContainerComponent that contains SomeSection and OtherSection, then handle the staggering animations in the ContainerComponent's `componentWillEnter` and `componentWillLeave`

```js
<ReactTransitionGroup>
  <CurrentPage>
    <ReactTransitionGroup>
      <ContainerComponent/>
    </ReactTransitionGroup>
  </CurrentPage>
  <OtherPage>
</ReactTransitionGroup>
```

```js
class ContainerComponent extends Component {

  componentWillEnter () {
    animate.staggerFromTo([this.someSection, this.otherSection], ...etc)
  }

  render () {
    return (
      <div>
        <SomeSection ref={c => this.someSection}/>
        <OtherSection ref={c => this.otherSection}/>
      </div>
    );
  }
}
```

btw closing as it's not an issue on this lib, but feel free to continue commenting on the thread :)

**Comment by RanzQ** [comment]
@cheapsteak Ok, I'll do some experiments. That seems like a solution, thank you. Actually I found a lib that does this: https://www.npmjs.com/package/react-css-stagger, but I prefer JS animations.
