### ISSUE TITLE
Will this solve my fade out then slide up problem?

### ISSUE THREAD

**Issue by no1melman** [cheapsteak/react-transition-group-plus#19]
I'm liking the look of the additional functionality here. I've posted a [question on stackoverflow](https://stackoverflow.com/questions/45304020/react-transition-group-slide-elements-up) and was wondering if this library could help me solve my problem? If so, how?

**Comment by cheapsteak** [comment]
Hi, thanks for reaching out :)

Unfortunately this library (and the one it was based on) only handles things coming in and out, not transitioning between states (in this case "being in the 2nd row" -> "being in the 1st row")

What I would do in this case is to separate the animations out into two separate ones.  
- Each item would animate themselves in/out  
- The "Y" position of each item would be calculated based on its position in the list (e.g. 0, 1, 2, 3, 4 etc), which can be passed in from the list 

This way once, say, the 1st item finishes animating itself out, the list would be updated so the items previously in the 2nd, 3rd, and 4th rows would now be told they're in the 1st, 2nd, and 3rd row, and have a new Y position they should be in, and transition to those new Y positions

I would recommend looking at [react-motion](https://github.com/chenglou/react-motion) for transitioning on the Y

(I'll make the same comment on SO :)
