### ISSUE TITLE
React 16 breaks this 

### ISSUE THREAD

**Issue by nudoru** [cheapsteak/react-transition-group-plus#23]
Appears that React 16 removed 'react/lib/ReactTransitionChildMapping' which this lib depends on.

**Comment by cheapsteak** [comment]
thanks for letting me know! fixing now

**Comment by cheapsteak** [comment]
Just released 0.5.0 on npm, let me know if it worked?

**Comment by cheapsteak** [comment]
oops, actually please use 0.5.1

**Comment by nudoru** [comment]
Thanks for quick update!

But, it's failing for me on 
Module not found: Error: Can't resolve 'lodash.keyBy' in '/usr/src/app/node_modules/react-transition-group-plus/src'

**Comment by cheapsteak** [comment]
Apologies! Please try 0.5.2

My mac fs is not case sensitive and missed the typo, should have been all lowercase `lodash.keyby`

**Comment by nudoru** [comment]
It's working great! Thank you again for your quick work to fix it.
