### ISSUE TITLE
React owner error

### ISSUE THREAD

**Issue by jnatherley** [cheapsteak/react-transition-group-plus#25]
Version:  `0.5.2`,
React Version: `16.2.0`

```
Element ref was specified as a string (.0) but no owner was set. You may have multiple copies of React
```
Example usage
```

<ReactTransitionGroupPlus>
                    {isVisbible && <span>test</span>}
</ReactTransitionGroupPlus>
```

Currently trying to work on authoring a React library using webpack, i'm excluding all node_modules through the 'webpack-node-externals' plugin and have react, react-dom and react-transition-group-plus listed as peerDependencies. This error pops up when trying to consume the library in another pacage. Any recommendations on where to look to resolve the issue?

Awesome library by the way! 👍

**Comment by jnatherley** [comment]
It might be due to two copies of ReactTransitionGroupPlus being loaded, removing it from the library package made them same code work directly. Any ideas on how to stop ReactTransitionGroupPlus being bundled with webpack?

**Comment by cheapsteak** [comment]
Hi, maybe [webpack.IgnorePlugin](https://webpack.js.org/plugins/ignore-plugin/) would work? Personally haven't tried using that before
