### ISSUE TITLE
Cannot read property 'componentWillAppear' of undefined

### ISSUE THREAD

**Issue by corysimmons** [cheapsteak/react-transition-group-plus#28]
Copied sandbox from http://reactcommunity.org/react-transition-group/#TransitionGroup

Dropped in `import TransitionGroupPlus from 'react-transition-group-plus'`, removed `TransitionGroup`, used `<TransitionGroupPlus>` where appropriate.

Get this error. I think maybe react-transition-group removed that lifecycle method by default. I tried adding the `appear` prop to `<TransitionGroupPlus>` per http://reactcommunity.org/react-transition-group/#TransitionGroup-prop-appear but still no luck.

Version numbers of deps are in the sandbox.

**Comment by cheapsteak** [comment]
Hi there, react-transition-group v2's api isn't compatible with the original react-transition-group, and their docs for their v2 won't be compatible with this library

These are the docs for the original: 
https://reactjs.org/docs/animation.html#low-level-api-reacttransitiongroup

Hope that helps :)

**Comment by corysimmons** [comment]
>their v2 won't be compatible with this library

Bummer :(
