### ISSUE TITLE
Peer dependency warning from react@^15.0.1

### ISSUE THREAD

**Issue by nksfrank** [cheapsteak/react-transition-group-plus#29]
I'm seeing a warning that I don't fulfill the react peer dependency.
I'm using react 16.1.1 in my package.json
![image](https://user-images.githubusercontent.com/7352072/37825381-e678978e-2e8f-11e8-8800-93472deaff4b.png)

**Comment by cheapsteak** [comment]
Thanks for the heads up!
Published 0.5.3 with the version on the peer dependency set to *

**Comment by nksfrank** [comment]
thanks for the quick response. that solved it for me.
