### ISSUE TITLE
[Question] How to animate the component onMount?

### ISSUE THREAD

**Issue by amorino** [cheapsteak/react-transition-group-plus#6]
ReactTransitionGroup has `transitionAppear={true}` for initial animation onMount, is is possible with this library?

Thanks for this awesome library!

**Comment by cheapsteak** [comment]
Hi there,

`transitionAppear` seems to be a `ReactCSSTransitionGroup` prop?

This library functions nearly identical to the lower level ReactTransitionGroup api (the initial code was forked from there), just with cancellation and ordering, it would be useful to reference [the docs there](https://facebook.github.io/react/docs/animation.html#low-level-api-reacttransitiongroup).

To perform initial animations on mount, you can use the `componentWillAppear` hook

My recommendation would be to have an `animateIn` function that has the code for actually performing the animations, and call the function from `componentWillAppear` and `componentWillEnter`

Hope that answers your question :)
